name: C/C++ CI

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
    windows:
        runs-on: windows-latest
      
        steps:
          - uses: actions/checkout@v3

          - name: sdl
            run: |
                bash
                git clone https://github.com/libsdl-org/SDL.git -b SDL2
                cd SDL
                mkdir build
                cd build
                bash ../configure
                make
                make install
          
          - name: make
            run: make
    

          - uses: actions/upload-artifact@v4.2.0
            with:
              name: exe
              path: ./*.exe
    
    linux:
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v3

          - name: sdl
            run: |
                git clone https://github.com/libsdl-org/SDL.git -b SDL2
                cd SDL
                mkdir build
                cd build
                ../configure
                make
                sudo make install
                git clone --recursive https://github.com/libsdl-org/SDL_ttf.git
                sudo apt install cmake -y
                cd SDL_ttf
                mkdir out
                cd out 
                cmake ..
                make
                sudo make install
                
          - name: make
            run: make

          - uses: actions/upload-artifact@v4.2.0
            with:
              name: linux
              path: ./*
