name: C/C++ CI

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
    windows:
        runs-on: windows-latest
      
        steps:
          - uses: actions/checkout@v3

          - uses: cygwin/cygwin-install-action@v2
            with:
              packages: gcc-core libargp-devel make build-essential git cmake ninja-build libudev-dev gcc-6 g++-6 sdl sdl2
          
          - name: make
            run: make
    

          - uses: actions/upload-artifact@v4.2.0
            with:
              name: exe
              path: ./*.exe
    
    linux:
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v3

          - name: wah
            run: sudo apt install gcc-core libargp-devel make build-essential git cmake ninja-build libudev-dev gcc-6 g++-6 sdl sdl2 -y
          - name: make
            run: make

          - uses: actions/upload-artifact@v4.2.0
            with:
              name: linux
              path: ./*
